### ISSUE TITLE
Create formal header for backwards compatibility

### ISSUE THREAD

**Issue by JamesxX** [norstone-tech/scon#13]
SCON needs a formal header, between the magic number and the data, storing at the very least the version number of the specification followed by the creating library, to allow for backwards compatibility in more sophisticated implementations.

This would also allow SCON to adopt a format that can be spread over numerous files, or even a hash of the current file.

**Comment by ARitz-Cracker** [comment]
SCON3 Now has extensible types, which solve the whole backward/forward compatibility thing.
